### ISSUE TITLE
Necessary to add 'reconnect: true' to thinking_sphinx.yml

### ISSUE THREAD

**Issue by mipearson** [pat/ts-delayed-delta#36]
Something to do with delayed_job & rails & daemon & thinking_sphinx results in random but very frequent (900k total count over two weeks) "MySQL server has gone away" errors in FlagAsDeletedJob since I upgraded to TS3.

Adding the following to thinking_sphinx.yml worked around this issue:

``` yaml
production:
  # ...
  connection_options:
    reconnect: true
```
